[build]
  publish = "public"
  command = "hugo"

[build.environment]
HUGO_VERSION = "0.145.0"

[context.production.environment]
HUGO_VERSION = "0.145.0"
HUGO_ENV = "production"
GO_VERSION = "1.24.0"

