[build]
  publish = "public"
  command = "npm install --save-dev autoprefixer && npm install --save-dev postcss-cli && npm install -D postcss && hugo --gc --minify --baseURL https://openreports.io/"

[context.production.environment]
HUGO_VERSION = "0.145.0"
HUGO_ENV = "production"
GO_VERSION = "1.24.0"

