# Top-level navigation (horizontal)

[[main]]
  name = "About"
  weight = 100
  url = "#about"

[[main]]
  name = "Community"
  weight = 300
  url = "#community"

[[main]]
  name = "Docs"
  weight = 300
  url = "/docs"